name: Deploy to GCP on tag

on:
  push:
    tags:
      - '*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Google Cloud CLI
      uses: google-github-actions/setup-gcloud@v0.2.0
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Deploy to GCP
      run: |
        ssh -i ${{ secrets.GCP_HOST }} ${{ secrets.GCP_USER }}@${{ secrets.GCP_HOST }} '
          cd ./deploy/deploy-test &&
          git fetch --all &&
          git checkout main &&
          git pull &&
          ./gradlew clean build --exclude-task test && 
          cd ../ &&
          ./stop.sh && 
          ./start.sh
        '
